package com.lzn.shardingsphere.model;

import java.util.Date;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.order_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.goods_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.goods_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.product_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.product_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.product_price
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Long productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.quantity
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item.create_time
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_id
     *
     * @return the value of t_order_item.order_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_id
     *
     * @param orderId the value for t_order_item.order_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.goods_id
     *
     * @return the value of t_order_item.goods_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.goods_id
     *
     * @param goodsId the value for t_order_item.goods_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.goods_name
     *
     * @return the value of t_order_item.goods_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.goods_name
     *
     * @param goodsName the value for t_order_item.goods_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.product_id
     *
     * @return the value of t_order_item.product_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.product_id
     *
     * @param productId the value for t_order_item.product_id
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.product_name
     *
     * @return the value of t_order_item.product_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.product_name
     *
     * @param productName the value for t_order_item.product_name
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.product_price
     *
     * @return the value of t_order_item.product_price
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Long getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.product_price
     *
     * @param productPrice the value for t_order_item.product_price
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.quantity
     *
     * @return the value of t_order_item.quantity
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.quantity
     *
     * @param quantity the value for t_order_item.quantity
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.create_time
     *
     * @return the value of t_order_item.create_time
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.create_time
     *
     * @param createTime the value for t_order_item.create_time
     *
     * @mbg.generated Fri May 22 21:11:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}